services:
  mongodb:
    image: 'mongo:5.0'
    environment:
      - 'MONGO_INITDB_DATABASE=academia'
      - 'MONGO_INITDB_ROOT_USERNAME=academia'
      - 'MONGO_INITDB_ROOT_PASSWORD=academia123'
    ports:
      - '27017'