cmd:
  shell: ${CMD_SHELL}
influxdb:
  url: ${INFLUX_DB_URL}
  org-name: ${INFLUX_DB_ORG_NAME}
  bucket-name: ${INFLUX_DB_BUCKET_NAME}
  token: ${INFLUX_DB_TOKEN}
repository:
  clone-directory: ${REPOSITORY_CLONE_DIRECTORY}
spring:
  config:
    import: classpath:local.yml
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: ${MONGO_DB_PORT}
      authentication-database: ${MONGO_DB_AUTH_DB}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: ${MONGO_DB_DB_NAME}
run-config:
  tracer-name: ${RUN_CONFIG_TRACER_NAME}
  execution-limit: ${RUN-CONFIG_EXECUTION_LIMIT}
  from-file-id: ${RUN-CONFIG_FROM_FILE_ID}
  to-file-id: ${RUN-CONFIG_TO_FILE_ID}
  force-compute: ${RUN-CONFIG_FORCE_COMPUTE}
oracle:
  file-directory: ${ORACLE_FILE_DIRECTORY}
trace:
  file-directory: ${TRACE_FILE_DIRECTORY}
  cache-directory: ${TRACE_CACHE_DIRECTORY}
  enable-mongodb: ${TRACE_ENABLE_MONGODB}