cmd:
  shell: ${CMD_SHELL}
influxdb:
  url: ${INFLUX_DB_URL}
  org-name: ${INFLUX_DB_ORG_NAME}
  bucket-name: ${INFLUX_DB_BUCKET_NAME}
  token: ${INFLUX_DB_TOKEN}
repository:
  clone-directory: ${REPOSITORY_CLONE_DIRECTORY}
spring:
  config:
    import: classpath:local.yml
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: ${MONGO_DB_PORT}
      authentication-database: ${MONGO_DB_AUTH_DB}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: ${MONGO_DB_DB_NAME}
oracle:
  execution-limit: ${ORACLE_EXECUTION_LIMIT}
  from-file-id: ${ORACLE_FROM_FILE_ID}
  to-file-id: ${ORACLE_TO_FILE_ID}
  force-compute: ${ORACLE_FORCE_COMPUTE}