CMD_SHELL: sh
REPOSITORY_CLONE_DIRECTORY: ../academic
MONGO_DB_HOST: 127.0.0.1
MONGO_DB_PORT: 27017
MONGO_DB_AUTH_DB: admin
MONGO_DB_USERNAME: cto
MONGO_DB_PASSWORD: cto123
MONGO_DB_DB_NAME: cto
INFLUX_DB_URL: http://localhost:8086
INFLUX_DB_ORG_NAME: RnD
INFLUX_DB_BUCKET_NAME: cto
INFLUX_DB_TOKEN: vOGZe-SQfYv1EV8cXz_KkKgVblZ3nBwNh54GlsA4Eo7woaRoOcV-1Z7d9gD-B0-UDI8YdalBj60F_J26WKX0cw==
RUN-CONFIG_EXECUTION_LIMIT: 200
RUN_CONFIG_TRACER_NAME : historyFinder
#RUN_CONFIG_TRACER_NAME : historyFinder,codeShovel,codeTracker,intelliJ,gitLineRange,gitFuncName
RUN-CONFIG_FROM_FILE_ID: 17
RUN-CONFIG_TO_FILE_ID: 17
RUN-CONFIG_FORCE_COMPUTE: true
ORACLE_FILE_DIRECTORY: oracle
TRACE_FILE_DIRECTORY: trace